modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
  http_any:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
      valid_status_codes: []  # Accept any status code
  http_2xx_4xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
      valid_status_codes: [200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 400, 401, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423, 424, 425, 426, 428, 429, 431, 451]  # Accept 2xx and 4xx
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp